# Generated by Django 4.2.22 on 2025-06-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='external_link',
            field=models.URLField(blank=True, help_text='(Optional) Link to the original recipe'),
        ),
    ]
